[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "oresat-random-scripts"
version = "0.1"
dependencies = [
  "oresat-configs==0.8.0",
  "requests"
]

[tool.setuptools]
# We don't want to build a real package from the scripts (yet)
packages=[]
